rails:
  build: .
  restart: always
  env_file: ../../.env.production
  volumes:
    - /home/app/rails/rnplay:/app
    - /home/app/repos:/var/repos
  links:
    - postgres
    - cache
    - redis
  environment:
    RAILS_ENV: production
    PASSENGER_RAILS_ENV: production
    VIRTUAL_HOST: rnplay.org,www.rnplay.org

postgres:
  restart: always
  env_file: ../../.env.production
  image: postgres

packager080rc2:
  restart: always
  image: "packager:0.8.0-rc.2"
  command: "node node_modules/react-native/packager/packager.js --port 8081"
  env_file: ../../.env.production
  environment:
    VIRTUAL_HOST: packager080rc2.rnplay.org
  volumes:
    - /home/app/rails/rnplay/app_js:/app/js 

packager0100rc:
  restart: always
  image: "packager:0.10.0-rc"
  env_file: ../../.env.production
  environment:
    VIRTUAL_HOST: packager0100rc.rnplay.org
  volumes:
    - /home/app/rails/rnplay/app_js:/app/js

redis:
  restart: always
  image: redis

cache:
  restart: always
  image: memcached

worker:
  restart: always
  build: .
  command: bundle exec sidekiq -e production -c 25
  volumes:
    - /home/app/rails/rnplay:/app
  env_file: ../../.env.production
  links:
    - postgres
    - redis
    - cache

grack:
  image: grack-docker
  volumes:
    - /home/app/repos:/var/repos
    - /home/app/rails/rnplay:/rails
  links:
    - postgres
  environment:
    VIRTUAL_HOST: git.rnplay.org
