rails:
  build: .
  restart: always
  env_file: ../../.env.production
  volumes:
    - /home/app/rails/rnplay:/app
    - /home/app/repos:/var/repos
  links:
    - postgres
    - cache
    - redis
  environment:
    RAILS_ENV: production
    PASSENGER_RAILS_ENV: production
    VIRTUAL_HOST: rnplay.org,www.rnplay.org

postgres:
  restart: always
  env_file: ../../.env.production
  image: postgres

packager0110rc:
  restart: always
  image: "packager:0.11.0-rc"
  env_file: ../../.env.production
  environment:
    VIRTUAL_HOST: packager0110rc.rnplay.org
  volumes:
    - /home/app/rails/rnplay/app_js:/app/js

packager0110:
  restart: always
  image: "packager:0.11.0"
  env_file: ../../.env.production
  environment:
    VIRTUAL_HOST: packager0110.rnplay.org
  volumes:
    - /home/app/rails/rnplay/app_js:/app/js

packager0114:
  restart: always
  image: "packager:0.11.4"
  env_file: ../../.env.production
  environment:
    VIRTUAL_HOST: packager0114.rnplay.org
  volumes:
    - /home/app/rails/rnplay/app_js:/app/js

packager0130rc:
  restart: always
  image: "packager:0.13.0-rc"
  env_file: ../../.env.production
  environment:
    VIRTUAL_HOST: packager0130rc.rnplay.org
  volumes:
    - /home/app/rails/rnplay/app_js:/app/js

redis:
  restart: always
  image: redis

cache:
  restart: always
  image: memcached

worker:
  restart: always
  build: .
  command: bundle exec sidekiq -e production -c 25
  volumes:
    - /home/app/rails/rnplay:/app
  env_file: ../../.env.production
  links:
    - postgres
    - redis
    - cache

grack:
  image: grack-docker
  volumes:
    - /home/app/repos:/var/repos
    - /home/app/rails/rnplay:/rails
  links:
    - postgres
  environment:
    VIRTUAL_HOST: git.rnplay.org
