rails:
  image: rnplay_rails
  restart: always
  env_file: ../../.env.staging
  volumes:
    - /home/app/rails/rnplay_staging:/app
    - /home/app/repos:/var/repos
  links:
    - postgres
    - cache
    - redis
  environment:
    RAILS_ENV: staging
    VIRTUAL_HOST: staging.rnplay.org

worker:
  restart: always
  image: rnplay_sidekiq
  volumes:
    - /home/app/rails/rnplay:/app
  env_file: ../../.env.staging
  links:
    - postgres
    - redis
    - cache

postgres:
  restart: always
  env_file: ../../.env.staging
  image: postgres

redis:
  restart: always
  image: redis

cache:
  restart: always
  image: memcached

grack:
  image: grack-docker
  volumes:
    - /home/app/repos:/var/repos
    - /home/app/rails/rnplay_staging:/rails
  links:
    - postgres

packager:
  restart: always
  image: "packager:0.11.0-rc"
  env_file: ../../.env.staging
  environment:
    VIRTUAL_HOST: packager-staging.rnplay.org
  volumes:
    - /home/app/rails_staging/rnplay/app_js:/app/js

