rails:
  image: rnplay_rails
  restart: always
  env_file: ../../.env.staging
  volumes:
    - /home/app/rails/rnplay_staging:/app
    - /home/app/repos:/var/repos
  links:
    - postgres
    - cache
    - redis
  environment:
    PASSENGER_APP_ENV: staging
    RAILS_ENV: staging
    VIRTUAL_HOST: staging.rnplay.org

worker:
  restart: always
  image: rnplay_sidekiq
  command: bundle exec sidekiq -e staging -c 25
  volumes:
    - /home/app/rails/rnplay_staging:/app
  env_file: ../../.env.staging
  links:
    - postgres
    - redis
    - cache

postgres:
  restart: always
  env_file: ../../.env.staging
  image: postgres

redis:
  restart: always
  image: redis

cache:
  restart: always
  image: memcached

grack:
  image: grack-docker
  volumes:
    - /home/app/repos:/var/repos
    - /home/app/rails/rnplay_staging:/rails
  links:
    - postgres
